### ISSUE TITLE
Reorganize column order in renderDataTable for better readability

### ISSUE THREAD

**Issue by felbasa** [EstadisticasPR/ViolenciaGeneroPR#29]
### Issue Description:
Reorganize the columns in the renderDataTable function to improve user readability, arranging them in the order: **index, category, value**.

### Expected Behavior:
Columns should be displayed in the order: **index, category, value**.

### Actual Behavior:
Columns are not currently organized in this order.

**Comment by genesisperez19** [comment]
closed with #68
