### ISSUE TITLE
Modify hover tooltip functionality in mapping helper functions

### ISSUE THREAD

**Issue by felbasa** [EstadisticasPR/ViolenciaGeneroPR#34]
### Issue Description:
Improve the hover tooltip functionality in renderMap() and renderMapGroup() for better user experience.

### Expected Behavior:
Hover tooltips should provide clear and useful information.

### Actual Behavior:
Hover tooltips are not as user-friendly as desired.

### Modify tooltip in the following helper functions:
- [x] renderMap()
- [x] renderMapGroup()

**Comment by genesisperez19** [comment]
closed with #55
